로그인 활동 > 위,경도값 정확하지 않을 때, 지도 대신 이미지 렌더링 되도록 수정
Instagram-Clone-Coding/React_instagram_clone pull request #125
Opened 2023-04-03 09:27 UTC by live-small

## 작업사항

- 로그인 활동에서, 어디서 로그인했는지 위,경도값을 서버로부터 받아와 네이버 지도에 렌더링합니다.
- 이때, 위,경도값이 부정확한 경우, 지도에 이상한 곳(바다 한가운데..)이 잡힙니다. 
- 부정확한 경우, 지도를 렌더링할 필요가 없기에 이미지로 변경했습니다. 
- 또, 위치를 확인할 수 없다고 사용자에게 보여주기위해 이미지에 스타일을 추가했습니다. 

## 구현이미지 
<img width="1066" alt="스크린샷 2023-04-01 오전 1 02 34" src="https://user-images.githubusercontent.com/70274947/229468937-b1e2e12f-ea0e-4ea0-9218-59e6e85633f4.png">

## 참고
위, 경도값을 받아오는 api가 쿠키가 필요하기때문에 로컬서버에서는 테스트 해볼 수 없습니다 ㅜㅜ(https 적용하면 로컬에서도 테스트 가능합니다..! 백엔드 분들께 말씀드렸으니까, 기다려보죠!) 
그래서 더미데이터 만들어서 UI 작업하고, pr올리기 전에 지웠습니다.

2023-04-18 15:07 UTC, kimyoungyin requested changes

2023-04-18 15:07 UTC, kimyoungyin commented on src/utils/maps.ts
> +};
이 부분을 따로 뺀 이유가 있을까요? 재사용 될 일도 크게 없을 것 같아서요!

2023-04-18 17:19 UTC, live-small commented on src/utils/maps.ts
> +};
UI랑 로직를 분리하기 위해서 뺐습니다. tsx에서는 UI만, 로직은 utils 나 custom hook로, 관심사 분리하는 걸 선호해서요! 
재사용관점에서는 분리안해도 될 거 같은데, 관심사 분리(UI, 로직) 관점에서 나누게 되었어용 
영인님은 어떻게 생각하시나요? @kimyoungyin

2023-04-23 13:56 UTC, kimyoungyin commented on src/utils/maps.ts
> +};
아 좋은 것 같습니다! 

그런데 솔직히 저희가 초반부터 작업했을 때는 utils로 로직을 빼서 작업하는 컨벤션을 따르지 않다가 갑자기 들어온 느낌이라 ㅋㅋㅋ

저도 이 부분은 좋은 것 같아서 위 코드는 그대로 유지해도 좋을 것 같은데, 대신 `README.md`에 해당 부분을 추가해놓는 건 어떠세요? 저도 그 컨벤션 따라 작업하겠습니다.

@live-small

2023-04-23 15:20 UTC, live-small commented on src/utils/maps.ts
> +};
@kimyoungyin 추가해놨습니다! 보시고 승인부탁드릴게용

2023-04-23 15:43 UTC, kimyoungyin approved these changes

2023-04-24 07:12 UTC, merged