profile
Instagram-Clone-Coding/React_instagram_clone pull request #46
Opened 2022-03-15 07:24 UTC by ChanhyukPark-Tech

- 에디터 변경으로인한 전체 프로필 파일 프리티어 적오요
- [프로필 페이지에서 메세지 보내기 버튼 누르면 DM 페이지로 이동해서 메세지 전송가능](https://github.com/Instagram-Clone-Coding/React_instagram_clone/commit/c757aeac72d6de17c9c187d9697168bd244fc62d)
- [프로필 페이지에서 게시글/태그/저장된 이미지가 한개도 없을경우 UI 처리](https://github.com/Instagram-Clone-Coding/React_instagram_clone/commit/888a9fd57486c8bd65192133e32a9b79b73dcd60)
- [fix: 프로필페이지 진입시 기본 게시글은 게시물로 설정 (태그됨이나 저장됨이아님)](https://github.com/Instagram-Clone-Coding/React_instagram_clone/commit/49f359a4ec6e3b74d6ff97b5a473982bc76ee56c)

2022-03-15 10:33 UTC, kimyoungyin commented on src/components/Profile/Header/ProfileHeader.tsx
> +        dispatch(selectView("chat"));
비동기 dispatch가 rejected되었을 때도  181줄에 dispatch가 실행되게 되는데, 대신 makeRoom thunk 내부에서 
비동기 작업이 성공했을 때만 thunkOptions.dispatch()를 해주는게 어떨까요?

2022-03-15 10:53 UTC, kimyoungyin requested changes
sprite6과 동일한 파일이 sprite2인 것 같은데 혹시 찬혁님은 없나요? 있으면 sprite6 제거 부탁드립니다!

2022-03-15 10:57 UTC, kimyoungyin commented on src/components/Profile/Article/Article.tsx
> +            )}
리터럴+유니온 타입으로 `currentCategory`에 적용할 거면 initialState(게시물 state)를 빈 문자열("")보단 의미를 가지는 명시적인 문자 리터럴이었으면 좋겠습니다.

예시: "article"

2022-03-15 10:59 UTC, kimyoungyin commented on src/components/Profile/Article/Article.tsx
> +            )}
"uploaded"가 다른 리터럴 타입들을 살펴봤을 때 괜찮은 것 같기도 하네요 ㅎㅎ

2022-03-15 11:15 UTC, kimyoungyin commented on src/components/Profile/Category.tsx
> +    }, []);
저장됨(saved) 상태에서 게시글을 살펴보다가 다른 곳을 잠깐 둘러보고 이전으로 돌아갔을 때는 `"saved"`가 유지되어야 하지 않을까요?

아마 실제 인스타그램에서는 이런 `history` 때문에 url에 saved, tagged를 적용한 것 같은데, 이와 동일하게 하기 위한 제안을 드리자면
1. Routes에서 각 url에 따른 라우트를 판 뒤에 각각 route에 같은 `Category` 컴포넌트를 렌더링하게 함(다른 path로 접근 시도시 기본 "uploaded"로 redirect 혹은 404페이지(인스타그램은 404페이지더라구요)
2. useParam과 같은 hook으로 받은 path data를 line 57과 같이 할당
3. (선택)useEffect에서 해당 path 정보를 담아 dispatch하여 `currentCategory`를 변경
4. 2나 3으로 받은 currentCategory로 비동기 dispatch 혹은 ui 변경

사실 `currentCategory` state가 굳이 필요없을 것 같아보이긴 합니다.
다른 route에서도 `currentCategory` state가 쓰일 것 같으면 유지해야겠지만요!

2022-03-15 11:18 UTC, ChanhyukPark-Tech commented on src/components/Profile/Header/ProfileHeader.tsx
> +        dispatch(selectView("chat"));
좋은 의견같습니다! 그렇게 진행되어야겠네요~!😄

2022-03-15 11:21 UTC, ChanhyukPark-Tech commented on src/components/Profile/Article/Article.tsx
> +            )}
리뷰감사합니다.
이 부분에서 "" / "tagged" / "saved" 
로 설정한 이유는 백엔드의 API endpoint 때문입니다!
<img width="1175" alt="Screen Shot 2022-03-15 at 8 19 43 PM" src="https://user-images.githubusercontent.com/69495129/158366916-2f55883d-663b-4c71-a698-dc7049332efa.png">

위 사진은 게시글을 요청하는 API 의 엔드포인트인데 공통적으로 변수를 이용해서 사용하기위해서 네이밍을 저렇게 진행하였습니다!

<img width="541" alt="Screen Shot 2022-03-15 at 8 20 59 PM" src="https://user-images.githubusercontent.com/69495129/158367121-dfe725c9-def0-4ba8-9925-71e5364b5f47.png">

2022-03-15 11:24 UTC, ChanhyukPark-Tech commented on src/components/Profile/Category.tsx
> +    }, []);
@kimyoungyin 
리뷰 감사합니다.
59~61번째 코드를 삽입하기전엔 영인님 말씀대로
`저장됨(saved) 상태에서 게시글을 살펴보다가 다른 곳을 잠깐 둘러보고 이전으로 돌아갔을 때는 "saved"가 유지되었었습니다!`
하지만, 인스타에서 저장됨을보다가 다른사람 혹은 홈페이지의 피드를 살피고 다시 프로필로오면 default 는 게시물로 되는것 같습니다.
그래서 항상 프로필을 오면 default로 게시물을 보도록 세팅해줬습니다!

2022-03-15 11:33 UTC, kimyoungyin commented on src/components/Profile/Article/Article.tsx
> +            )}
아하
혹시 보통 api와 변수를 통일시키는게 일반적인가요? 그렇다면 괜찮을 것 같은데,
그게 아니라면 프론트단에서 보기 좋은 코드는 "uplaoded"가 좋은 것 같아요!
위 thunk에서 currentCategry를 받아오고 switch문에서 case가 "uploaded"로 바뀌기만 하면 되지 않을까요...?

스크린샷 코드를 보니 리팩토링 사항이 생겨서 남깁니다.
```ts
const url = `/accounts/${payload.username}/posts/${currentCategory !== "" ? currentCategory + "/" : ""}recent`
// "upload"로 변경한다면 
const url = `/accounts/${payload.username}/posts/${currentCategory !== "uploaded" ? currentCategory + "/" : ""}recent `
```
이렇게 하면 `switch...case`문이 필요 없습니다!

2022-03-15 11:35 UTC, kimyoungyin commented on src/components/Profile/Category.tsx
> +    }, []);
어떻게 저장됨 route에서 다른 사람 홈페이지/피드를 갔다가 돌아왔을 떄 유지되는 지 알 수 있을까요? 저는 유지되는 것 같아서 ㅠ

2022-03-15 15:08 UTC, ChanhyukPark-Tech commented on src/components/Profile/Header/ProfileHeader.tsx
> +        dispatch(selectView("chat"));
[fix: 비동기 작업 성공시에만 chat View 로 이동하게 처리 (영인님 피드백)](https://github.com/Instagram-Clone-Coding/React_instagram_clone/pull/46/commits/1ccaec71848611db4c6159f240fc194a3e7f31ea)

감사합니다^^

2022-03-15 15:08 UTC, ChanhyukPark-Tech commented on src/components/Profile/Article/Article.tsx
> +            )}
[refactor: profile page category "" 로 처리했던 default 가독성을 위해 uploaded로 수정](https://github.com/Instagram-Clone-Coding/React_instagram_clone/pull/46/commits/ea459ac656a7531de336cd17ca59f6429d9f18a4)

피드백 감사합니다^^ 가독성이나 유지보수측면에서 역시 uploaded가 좋았네용

2022-03-15 15:09 UTC, ChanhyukPark-Tech commented on src/components/Profile/Category.tsx
> +    }, []);
뒤로가기를 하면 영인님말씀대로 라우트가 유지되네요.
나의 프로필에서 저장됨 상태로 다른사람 프로필 갔다가 나의프로필로 오면 저장됨이 아닌 게시물이 먼저 보이게됩니다 저는!

2022-03-16 01:07 UTC, kimyoungyin commented on src/components/Profile/Category.tsx
> +    }, []);
다시 마이프로필로 들어가는 건 /recent로 바로 가는 거기 때문에 당연히 그렇게 되는 건 맞는데 뒤로가기와 같이 history 측면에서는 제 의견이 맞는 것 같아서 수정해보는 건 어떨까요..?

2022-03-23 13:47 UTC, merged