Feature/login
Instagram-Clone-Coding/React_instagram_clone pull request #47
Opened 2022-03-15 13:38 UTC by live-small

- 진행사항 
    - 버튼 로딩 상태, 각 컴포넌트가 아니라 authSlice에서 관리하는 걸로 통일 
    - 비밀번호 재설정 화면 구현중인데, 수요일까진 꼭 마무리하겠습니다.

2022-03-16 08:28 UTC, ChanhyukPark-Tech commented on src/app/store/ducks/auth/authSlice.ts
> +        },
위 방법이 좋을지 아니면 signUpButtonLoading 이라는 하나의 리듀서로 
외부에서 인자로 action.payload 를 받아서 세팅해주는게 좋을지 헷갈리네용😅
아무리 하나의 리듀서가 하나의 역할만 한다고 해도 true / false 로 셋팅해주는 리듀서는 한개면 충분할거같다고 개인적으로 생각합니다 😄

2022-03-16 08:57 UTC, live-small commented on src/app/store/ducks/auth/authSlice.ts
> +        },
그쵸. 모든 버튼에 로딩처리를 하면서 리듀서를 하나씩 늘릴 때마다 찬혁님이 하신 생각이 들더라구요. 
또, 각 컴포넌트에서 useState로 관리하는 것보다 리덕스로 관리하는게 어떤 점에서 더 좋은지도 잘 모르겠더라구요. 
찬혁님은 혹시 처리하신 로딩을 action.payload로 받아서 세팅하셨나요?

2022-03-19 03:39 UTC, kimyoungyin reviewed
커밋에 어떤 컴포넌트에 대한 변화인지도 적어줬으면 좋을 것 같아요!

2022-03-19 04:16 UTC, kimyoungyin requested changes

2022-03-19 04:16 UTC, kimyoungyin commented on src/components/Auth/ResetPassword/index.tsx
>      };
실제 인스타그램에서 사용자 정보가 아예 없을 때 밑에서 notification이 뜨는데, 제가 만들어둔 `Notification`에 `text` props를 넣어서 redux boolean state로 5초 뒤 dispatch하여 꺼지는 방식으로 조작하시면 될 것 같습니다.

`styles/UI/Notification/Notification.tsx`에서 `Notification` 컴포넌트를 확인해보시고, `pages/Home/Home.tsx`에서 `Notification`을 가져와 어떻게 사용했는지 참고하시면 좋을 것 같아요.
<img width="1440" alt="스크린샷 2022-03-19 오후 1 03 22" src="https://user-images.githubusercontent.com/78777345/159105970-a6bf3682-24f8-4529-9377-1d964aeffa4b.png">

2022-03-20 12:55 UTC, live-small commented on src/components/Auth/ResetPassword/index.tsx
>      };
반영했습니다!

2022-03-20 12:59 UTC, live-small commented on src/app/store/ducks/auth/authSlice.ts
> +        },
동시에 loading값을 사용할 필요가 없어, isLoading 한 상태로 관리하는 거로 수정했고, action.payload로 true/false 받아와서 세팅하는거로 변경했습니다 😄

2022-03-22 12:25 UTC, ChanhyukPark-Tech commented on src/components/Auth/ResetPassword/InformSendingEmail.tsx
> +    return userData + "@" + emailAddress;
대박 잘짜셨네용..😄

2022-03-22 12:25 UTC, ChanhyukPark-Tech commented on src/app/store/ducks/auth/authSlice.ts
> +        },
이메일 리셋안시켜주면 어떤 문제가 생기나요?

2022-03-23 07:23 UTC, live-small commented on src/components/Auth/ResetPassword/InformSendingEmail.tsx
> +    return userData + "@" + emailAddress;
[과거에 공부한 정규표현식](https://github.com/live-small/problem-solving-/wiki/%5BRegExr%5D-lookarond-%EA%B3%B5%EB%B6%80#%EC%A0%95%EA%B7%9C%ED%91%9C%ED%98%84%EC%8B%9D-lookaround-)을 활용해봤습니다 ㅎㅎ 
다만 고민되는 게, konkuk.ac.kr 경우에선 ******.ac.kr 이 나을까요? ******.**.kr이 나을까요?

2022-03-23 07:28 UTC, live-small commented on src/app/store/ducks/auth/authSlice.ts
> +        },
state.resetPassword.email 상태값으로 /accounts/password/reset 라우터에서 보여주는 화면이 달라집니다. (컴포넌트명:ResetPassword)
비밀번호 재설정 할 수 있는 메일을 요청하는 폼화면을 보여줄지, 신청한 후 이메일 보냈다는 전송안내 화면을 보여줄 지 2가지가 있습니다.

2022-05-03 04:28 UTC, live-small commented on src/customAxios.ts
> -    return config; // 이거 실패 시, isLogin = false로 해서 화면 로그인으로
@ChanhyukPark-Tech @kimyoungyin 
request보내기 전, interceptor에 의해 토큰이 유효한지 체크하게 되는데, 
로그인 후 오랜시간이 지나 refresh토큰이 만료 돼 토큰 재발급에 실패할 경우, 새로고침해서 리덕스 상태값 초기화시켜 isLogin을 false로 만들게 되고, 로그인 페이지가 보이도록 수정했습니다. 

- 이전에 로그아웃 무한호출 에러는, 로그아웃 api에 access 토큰이 필요해서 인터셉터를 지나는 authorizedCustomAxios를 이용해 로그아웃을 호출하다보니, 로그아웃 request도 checktoken을 돌고 .. 도는 루프였습니다. 
- 토큰 재발급을 실패했을 때(refresh token만료), http-only 쿠키라 프론트에선 접근할 수 없었기에 로그아웃 api로 refresh token을 제거하려고 했습니다. 
- 하지만, 새로고침해서 로그인페이지로 이동해 로그인을 다시 할 경우, 만료된 refresh token이 있다면 제거 후 새로운 refresh token을 하기때문에 따로, 로그아웃 api를 호출해 제거해주지 않아도 되겠다는 생각을 했습니다. 
- 그래서, 토큰 재발급 실패 시 새로고침하는 코드로만 수정했습니다. 
- 추가로, authorizedCustomAxios를 이용해 호출하는 각 컴포넌트 thunk의 catch도 주석처리했습니다.

2022-05-03 09:26 UTC, ChanhyukPark-Tech commented on src/customAxios.ts
> -    return config; // 이거 실패 시, isLogin = false로 해서 화면 로그인으로
@live-small 이해했습니다.. 정리너무잘해주셨네요 감사합니다! 대박

2022-05-04 07:34 UTC, kimyoungyin commented on src/App.tsx
> +            } finally {
애초에 첫 렌더링 시 로그아웃 상태이기 때문에 catch문을 작성하지 않은 거라 보면 될까요?

2022-05-04 08:45 UTC, kimyoungyin commented on src/components/Auth/Line.tsx
> +    margin: ${(props) => (props.margin ? props.margin : "10px 40px 18px")};
```ts
props.margin || "10px 40px 18px"
```

2022-05-04 08:48 UTC, kimyoungyin commented on src/components/Auth/ResetPassword/HeaderBeforeLogin.tsx
> +                justify-content: flex-start;
기본값이 flex-start라 필요 없을 것 같습니다!

2022-05-04 12:38 UTC, live-small commented on src/App.tsx
> +            } finally {
넵 맞습니다! 기본값이 isLogin = false이기때문에 로그인 페이지로 넘어가기 때문입니다. 이외에는 500번대 서버내부에러인데, `interceptor.response.use`이용해서, response.status 500일 경우를 동시에 처리해도 될 거 같아서 500번대 에러는 아직 처리하지 않았습니다.

2022-05-04 12:44 UTC, ChanhyukPark-Tech commented on src/components/Auth/ResetPassword/HeaderBeforeLogin.tsx
> +        background-color: #fff;
${theme.color.bg_white} 사용해도 좋을 것 같스빈다

2022-05-04 12:44 UTC, ChanhyukPark-Tech commented on src/components/Auth/ResetPassword/HeaderBeforeLogin.tsx
> +                                    <Button bgColor="#ffffff" color="#0095F6">
theme.color.bg_white 사용해도 좋을 것 같습니다

2022-05-04 12:44 UTC, ChanhyukPark-Tech commented on src/components/Auth/ResetPassword/HeaderBeforeLogin.tsx
> +                                <Link to="/accounts/emailsignup">
카멜케이스 사용한다면 엔드포인트를 emailSignup 이라고해도좋지 않을까요?
저같은경우는 SignUp 이라고 할거같긴한데 signup 으로 통일하셨으니
emailSignup 도 좋은거같아요

2022-05-04 12:44 UTC, ChanhyukPark-Tech commented on src/components/Auth/ResetPassword/ResetPasswordEmailRequestForm.tsx
> +                        background-color: #fafafa;
${theme.color.bd_gray}
사용해도 좋을거같아요

2022-05-04 12:50 UTC, live-small commented on src/components/Auth/ResetPassword/HeaderBeforeLogin.tsx
> +                                <Link to="/accounts/emailsignup">
인스타그램 클론코딩이다보니, 인스타그램에 있는 라우터를 참고해서 `emailsignup`으로 정했었는데 가독성으로 보기엔 카멜 케이스가 좋을 거 같긴하네요. 찬혁님은 라우터를 대부분 카멜케이스로 작성하셨나요?

2022-05-04 12:57 UTC, live-small commented on src/components/Auth/ResetPassword/HeaderBeforeLogin.tsx
> +                justify-content: flex-start;
넵 수정하겠습니다!

2022-05-05 08:22 UTC, kimyoungyin commented on src/components/Auth/ResetPassword/ResetPasswordEmailRequestForm.tsx
> +                        color: #8e8e8e;
```ts
props.theme.font.gray
```

2022-05-05 08:23 UTC, kimyoungyin commented on src/components/Auth/ResetPassword/ResetPasswordEmailRequestForm.tsx
> +                        color: #8e8e8e;
반복되는 값 사용할 때는 theme 한번 들여다봐야 할 것 같아요 저도 깜빡깜빡해서.. ㅠㅠ

2022-05-05 13:49 UTC, live-small commented
### 변경사항 
- develop브랜치랑 충돌이 있어, 제 로컬 feature/login에서 develop을 merge해서 충돌해결 후, 해당pr로 develop에 머지하려고 했습니다. 
- 맥에서 머지하는 과정에서, 충돌 파일 커밋을 빼고 커밋 돼 해당 pr에서 여전히 develop이랑 충돌이 떴습니다. 
- git revert로 merge한 커밋을 취소한 후, 다시 머지를 진행해 confilct 해결했습니다. 

### 참고
- feature/login에서 작업하는 중 package-lock.json 파일변경이 있어서 develop과 다른 점이 5개 정도 있었습니다. 
- 대부분, 같은 package에 버전이 다른 문제여서 버전 업으로 충돌을 해결했습니다.

2022-05-05 14:22 UTC, kimyoungyin approved these changes
수고하셨습니다!! 늦게 리뷰 남겨서 죄송해요 ㅠㅠ

2022-05-05 14:22 UTC, kimyoungyin commented on src/components/Auth/ResetPassword/ResetPasswordEmailRequestForm.tsx
> +    );
useInput 내에 trim() 메서드로 공백을 제거하는 과정이 있는데 해당 validator가 필요할지 잘 모르겠네요?
아마 이걸 추가 안하면 현재 useInput onChange에서 빈 문자열에 대한 setIsValid를 실행하지 않기 때문에 추가하신 것 같은데,

useInput onChange에 어차피 trim()을 사용하는 겸 아래와 같이 변경하는 건 어떨까요? 다른 곳에서도 일단 빈 문자열일 경우 submit이 안되어야 할 것 같아서요! 이렇게 변경하면 빈 문자열에 대한 논리과정이 컴포넌트 밖에 useInput hook으로 뺄 수 있어서 좋을 것 같아요!
```ts
    const onChange = (event: ChangeEvent<HTMLInputElement>) => {
        const processdValue = event.target.value.trim();
        setValue(processdValue);
        if (processedValue) { // 추가한 조건문입니다
            onChangeValidator && setIsValid(onChangeValidator(processdValue));
        } else {
            setIsValid(false)
        }
    };
```

2022-05-05 14:22 UTC, kimyoungyin commented on src/components/Auth/SignUpForm/EmailConfirmForm.tsx
>          "",
여기서는 빈 문자열에 대한 validator가 필요 없는 걸까요?

2022-05-05 14:22 UTC, kimyoungyin commented on src/components/Auth/SignUpForm/InputAndButton.tsx
> +                // 네트워크 속도가 빠를경우, 동작이 안되는 것처럼 보임
네트워크 속도가 빠른 것에 대해서는 걱정 안하셔도 될 것 같아요!
대신 에러 메세지에 대해서는 자유긴 한데, 제가 만들어두었던 notification을 활용하는 건 어떨까요?

2022-05-05 14:22 UTC, kimyoungyin commented on src/customAxios.ts
> +            window.location.replace("/");
새로고침 부분이군요 좋습니다!

2022-05-05 14:22 UTC, kimyoungyin commented on src/@type/index.d.ts
> +
토큰 타입에 공통 부분만 같이 사용하고 나머지는 확장해서 사용하도록 말씀드렸던 부분이 반영되었네요! 감사합니다 ㅎㅎ

2022-05-05 14:46 UTC, kimyoungyin commented on src/components/Auth/ResetPassword/ResetPasswordEmailRequestForm.tsx
> +    );
혹시 빈 input이어도 isValid가 true여도 되는 경우가 있으시면 말씀해주세요!

2022-05-06 01:19 UTC, live-small commented on src/components/Auth/SignUpForm/InputAndButton.tsx
> +                // 네트워크 속도가 빠를경우, 동작이 안되는 것처럼 보임
좋습니다. 
영인님이 꼼곰하게 보셔서 이미 아시겠지만, 이 부분이회원가입 페이지에서 폼을 다 채우고 제출눌러서 유저가 작성한 이메일 인증할 때,
서버에서 이메일이 안보내졌을 때의 에러처리거든요. 
`조금만 있다 다시 버튼을 눌러주세요`이런 메시지를 notification에 넣으면 될 거 같습니다.

2022-05-06 01:30 UTC, live-small commented on src/components/Auth/SignUpForm/EmailConfirmForm.tsx
>          "",
네 맞습니다. 
- 이 부분은 회원가입 입력폼 작성 후, 이메일 유효체크를 위해 사용자가 적은 이메일에 인증코드를 보내게 되는데요.
- 인증코드가 성공적으로 갔을 때, 인증코드를 적을 페이지 컴포넌트입니다. 
- `useInput`3번째 인자인 onChange 이벤트 발생할때 체크하는 validator에 인증코드가 6글자인지 체크하는 함수를 이용합니다. 
- onChange validator의 isValid 값이 true 경우만 인증코드 제출버튼이 활성화됩니다. 
즉, 빈 문자열일 땐 제출 버튼을 누를 수 없기때문에 빈 문자열에 대한 validator가 필요없다고 생각해 구현하지 않았습니다.

2022-05-06 08:02 UTC, kimyoungyin commented on src/components/Auth/SignUpForm/EmailConfirmForm.tsx
>          "",
아 line84에 숨겨져있었네요.. 커밋 변경사항이 아니라 숨겨져있었군요
확인했습니다!

2022-05-07 14:56 UTC, live-small commented on src/components/Auth/ResetPassword/ResetPasswordEmailRequestForm.tsx
> +    );
꼼꼼한 코멘트와 조언 진심으로 감사합니다. 조금 고민하느라 이 코멘트만 늦게 답변드려서 죄송해요. 
- useInput 내에 trim()이 있지만 value.length > 0인 validator을 쓴 이유는
       - onChange 이벤트가 발생할 때마다 value.length를 체크해 발생하는 isValid 상태값을 제출버튼 활성화하는데 이용했기 때문입니다. 
      - 그리고, onChange이벤트로 입력된 값에서 공백을 제거한 값 후(trim), 0보다 큰지 체크하는 validator이 실행돼, 결과값`isValid`가 `true of false`로 할당되기에 따로 setIsValid(false)를 정의하지 않았습니다. 
      
      - 다른 곳에서도 빈 문자열일 경우를 위해 `setIsValid(false)`로 빼는 게 좋네요. 
      - 다만, value.length > 0인  onChangeValidator를 넘겨줘야만 setIsValid에 true값을 할당할 수 있기에 
              - 빈 문자열인지 체크하는 validator이 
              - 빈 문자열일경우, setIsValid(false)와 중복된다고 생각합니다. 
      - 빈 문자열인지 체크하는 value.length > 0인  onChangeValidator를 넘겨주지 않고, setIsValid를 제어할 수 있으면 좋을 거 같아요. 한번 고민해보겠습니다.

2022-05-08 12:52 UTC, merged