fix: 카테고리 변할때마다 배열 초기화
Instagram-Clone-Coding/React_instagram_clone pull request #58
Opened 2022-05-09 14:17 UTC by ChanhyukPark-Tech

## 개요
- 카테고리 변할때마다 배열을 초기화 해서 이전 카테고리의 해당하는 Posts 들이 리셋되도록함

## 작업사항

-   redux 에서 처리

## 주요 변경 로직

-   내용을 적어주세요.

2022-05-12 08:41 UTC, kimyoungyin requested changes

2022-05-12 08:41 UTC, kimyoungyin commented on src/app/store/ducks/profile/profileSlice.ts
> +            state.posts = [];
현재 catergory를 다시 클릭했을 때 초기화되는 예외 사항이 존재하네요. 이전 category와 같은지 확인한 후 다르다면 초기화 시켜주는 게 좋을 것 같습니다!

2022-05-12 08:43 UTC, kimyoungyin commented on src/app/store/ducks/profile/profileSlice.ts
> +            state.posts = [];
아니면 dispatch 하는 컴포넌트에서 현재 category와 비교한 후 다르다면 위 reducer를 실행하도록 수정해도 됩니다.

2022-05-16 11:56 UTC, ChanhyukPark-Tech commented on src/app/store/ducks/profile/profileSlice.ts
> +            state.posts = [];
감사합니다!! 제가 실수햇넹요 
[9b74c85](https://github.com/Instagram-Clone-Coding/React_instagram_clone/pull/58/commits/9b74c858652d9983f56233975deb977e36191f6c)

에서 수정하였습니다!

2022-05-21 15:26 UTC, merged