[setting 창 컴포넌트] - header의 프로필 이미지 클릭할 경우 보여지는 창 구현
Instagram-Clone-Coding/React_instagram_clone pull request #66
Opened 2022-06-16 15:13 UTC by live-small

## 개요
https://github.com/Instagram-Clone-Coding/React_instagram_clone/issues/62

## 작업사항
- header의 프로필 클릭 시, 나오는 창 구현
- 프로필, 설정, 로그아웃 클릭 시 link 이동(프로필, 설정), api 호출(logout api) 대응 
- useOutSideClick 커스텀 훅, 확장 

## 주요 변경 로직
- 로그아웃 api 호출 -> refresh token만 삭제됨. access token은 알아서 삭제해야함. 
   - 그래서, 로그아웃 api 호출이 성공할 경우, isLogin = false로 변경 -> route에서 isLogin 여부에 login 페이지로 이동하도록 구현

2022-06-21 15:53 UTC, kimyoungyin requested changes

2022-06-21 15:53 UTC, kimyoungyin commented on src/app/store/ducks/auth/authSlice.ts
> +                state.isLogin = false;
혹시 로그아웃 thunk가 rejected되었을 때에 에러 처리는 따로 필요 없을까요?
logout을 dispatch한 `SubNav` 컴포넌트에서도 따로 `unwrap()` 처리가 안되어 있어서 의도한 건지 알고 싶습니다!

2022-06-21 15:53 UTC, kimyoungyin commented on src/components/Common/Header/NavItems.tsx
> +    const [isClickedProfile, setIsClickedProfile] = useState(false);
클릭여부가 아니라 modal의 on/off를 결정하는 state이니 isAuthModalOn 이런 식으로 명명하는 게 나을 것 같습니다

2022-06-21 15:53 UTC, kimyoungyin commented on src/components/Common/Header/NavItems.tsx
> +    useOutsideClick(navContainerRef, setIsClickedProfile, triggerRef);
`setState`를 그대로 자식 컴포넌트에(prop) 혹은 매개변수로 주는 것은 좋지 않다고 알고 있습니다!
`setState` 자체가 비동기적으로 `state`를 변경하는 것이다 보니 충돌이 발생할 수 있으므로(예를 들어 re-rendering할 때) `setState`보다 화살표 함수 형태로 전달해주는 것이 좋습니다. 예를 들어
```ts
useOutsideClick(navContainerRef, () => setIsClickedProfile(false), triggerRef)
// 변수명보단 형식 참고
```
그래서 useOutsideClick hook의 전체적인 구조 또한 수정하는 것이 필요할 수 있겠네요.

2022-06-21 15:53 UTC, kimyoungyin commented on src/components/Common/Header/NavItems.tsx
> +    const triggerRef = useRef<HTMLDivElement | null>(null);
회의 때도 말씀드렸듯이, 그냥 변수명을 `trigger`로 하면
- 어떤 것을 trigger한다는 건지
- trigger하는 컴포넌트인지, trigger하는 함수인지

코드 가독성이 조금 안 좋은 것 같아서 예를 들면
`authModalTriggerComponent`,`subNavTriggerComponent` 혹은
`authModalTriggerElement`,`subNavTriggerElement` 와 같이 변경하면 좋을 것 같습니다. 
_사실 `subNav`라는 이름도 모달이라는 점을 고려하면 그리 좋은 이름은 아닌 것 같아 임의로 authModal이라고 해보았습니다. 이에 대해서는 해당 컴포넌트에서 작성할게요_

2022-06-21 15:53 UTC, kimyoungyin commented on src/components/Common/Header/NavItems.tsx
> +    }
아마 이 부분인 것 같은데 모달이 활성화되어있을 때 검은색 테두리가 정확히 중앙에 위치하지 않아서 이부분 확인 바랍니다!

2022-06-21 15:53 UTC, kimyoungyin commented on src/components/Common/Header/SubNav.tsx
> +        box-shadow: 0 0 5px 1px rgb(0 0 0 / 10%);
pointer 기준 container 위치가 인스타그램에 비해 오른쪽으로 치우쳐져 있습니다. 수정 부탁드려요!

2022-06-21 15:53 UTC, kimyoungyin commented on src/components/Common/Header/SubNav.tsx
> +const Container = styled.div`
Styled component라도 어떤 컴포넌트에 대한 것인지 알 수 있도록 변수명을 지어주셨으면 좋겠습니다!

2022-06-21 15:53 UTC, kimyoungyin commented on src/components/Common/Header/SubNav.tsx
> +            cursor: pointer;
각 option의 높이가 인스타그램과 약간 차이가 나서 간격이 좁혀져 있는데 확인 부탁드려요!

2022-06-21 15:53 UTC, kimyoungyin commented on src/components/Common/Header/SubNav.tsx
> +                </div>
이부분은 객체 배열 형태로 따로 정리한 후에 `Array.map`으로 처리한다면 코드가 더 깔끔할 것 같은데 어떠신가요?

2022-06-21 15:53 UTC, kimyoungyin commented on src/hooks/useOutsideClick.ts
> +    setter: Function,
`setState`를 직접 가져오는 건 좋지 않을 것 같습니다

2022-06-21 15:53 UTC, kimyoungyin commented on src/app/store/ducks/auth/authSlice.ts
> +                state.isLogin = false;
logout.rejected일 때는 따로 에러 처리할 필요가 없을까요?

2022-06-22 12:23 UTC, live-small commented on src/components/Common/Header/SubNav.tsx
> +                </div>
가독성에 그게 더 좋을 거 같아서 수정했습니다. 혹시 unique key는 어떻게 구하셨나요? unique key 만드는 함수 하나 만들어놓고 재사용하면 좋을 거 같아요!

2022-06-22 12:25 UTC, live-small commented on src/components/Common/Header/SubNav.tsx
> +const Container = styled.div`
해당 컴포넌트에서 wrapper를 container로 통일해서 작업했었는데, 어떤 부분인지 직관적으로 알기 어렵네요. 영인님은 어떤식으로 명명하셨나요?

2022-06-22 12:26 UTC, live-small commented on src/components/Common/Header/NavItems.tsx
> +    }
엇 진짜그러네요. 수정하겠습니다!

2022-06-23 07:31 UTC, live-small commented on src/components/Common/Header/NavItems.tsx
> +    }
수정했습니다!

2022-06-23 07:35 UTC, live-small commented on src/components/Common/Header/NavItems.tsx
> +    const triggerRef = useRef<HTMLDivElement | null>(null);
코드를 직접 짠 저만 이해할 수 있는 변수명이었네요..ㅠㅠ 다른 분들이 읽었을때도 고려해서 변수명 신경써서 작성하겠습니다! 
`subModalControllerRef`로 수정했습니다.

2022-06-23 07:38 UTC, live-small commented on src/components/Common/Header/NavItems.tsx
> +    useOutsideClick(navContainerRef, setIsClickedProfile, triggerRef);
### 0622 회의 
부모 상태값을 변경할 수 있는 setState를 직접 자식에게 넘겨주는 경우, 예상치 못한 값으로 변경될 가능성 높음. 
상태값 변경 함수를 만들어서, 넘기는 방법으로 수정하는 게 좋을 듯. 
-> 찬혁님이 만든 hooks이기에 찬혁님과 함께 얘기해보고 수정하기로 결정.

2022-06-27 12:48 UTC, merged