Feat/profile
Instagram-Clone-Coding/React_instagram_clone pull request #72
Opened 2022-06-29 15:06 UTC by ChanhyukPark-Tech

## 개요
1. 프로필편집에 비밀번호 재설정, 편집 부분에서 api호출해서 편집 성공하면 notification으로 편집 됐다고 알려주는 문구랑 추가하기 
- notification 컴포넌트 이용하면 될 거에요! 

2. 편집 -> 성별 클릭하면 모달창에서 토글로 옵션 선택하는 부분 
: 현재는 Input으로 되어있습니다!

## 작업사항

## 주요 변경 로직

-   Notification 컴포넌트에 reset 함수 받을 수 있도록 수정, 8.5s 가 지나면 다시 setState 시켜주도록.

2022-07-02 15:21 UTC, kimyoungyin requested changes
커밋 내역에 해당하지 않지만
1. 비밀번호 변경 버튼의 위치가 input과 동일하게 왼쪽 끝에 위치하도록 해주세요!
2. 비밀번호 변경 버튼을 클릭하여 비동기 호출 시 사용자가 현재 상황을 인식할 수 있도록, 인스타그램과 같이 `fullfilled` 혹은 `rejected` 되기 전 `pending` 동안에는 로딩 모양으로 버튼을 바꿔주세요!(이를 적용하려면 loading state를 사용해야 하기 때문에 해당 컴포넌트에서 이를 따로 만들거나 unwrap 처리를 하지 말고 전역 loading state를 활용하셔야 할 것 같습니다!)

2022-07-02 15:21 UTC, kimyoungyin commented on src/components/Edit/Menus/PasswordEdit.tsx
> +        const data = await dispatch(changePassword(body)).unwrap();
`unwrap()` 처리해서 컴포넌트 내에서 처리할 거라면 에러 처리가 필요하지 않을까요?

2022-07-02 15:21 UTC, kimyoungyin commented on src/components/Edit/Menus/PasswordEdit.tsx
> +            setMsg("두 비밀번호가 일치하는지 확인하세요");
먼저 기존 비밀번호가 일치하는 지 확인하고 이후에 새로운 두 비밀번호가 일치하는지 확인하는 게 사용자가 보기 좋을 것 같긴 한데,
이 부분은 `changePassword()`에서 같이 처리되는 부분일까요?

2022-07-02 15:21 UTC, kimyoungyin commented on src/components/Edit/Menus/PasswordEdit.tsx
> +            setMsg("두 비밀번호가 일치하는지 확인하세요");
기존 비밀번호가 일치하지 않은 경우 에러 메세지는 
"이전 비밀번호가 잘못 입력되었습니다. 다시 입력해주세요." 입니다.

2022-07-02 15:21 UTC, kimyoungyin commented on src/components/Edit/Menus/PasswordEdit.tsx
> +        const data = await dispatch(changePassword(body)).unwrap();
실제 인스타그램은 어떤지 모르지만 비밀번호 변경이 완료된 경우 보통 로그아웃 처리하고 다시 로그인하도록 하지 않나요? 아니면 상관없을까요..?

2022-07-02 15:21 UTC, kimyoungyin commented on src/components/Edit/Modal/ProfileGenderModal.tsx
> +        >
실제 인스타그램에서 브라우저가 특정 너비 이하일 때 `width`값이 100%로 변경되어 반응형 레이아웃으로 바뀌는데 이 부분 변경 부탁드립니다!

2022-07-02 15:21 UTC, kimyoungyin commented on src/components/Edit/Section/EditItemInput.tsx
>  const EditItemInput = ({ item, guide }: EditItemProps) => {
이 컴포넌트를 상위에서 map을 통해 렌더링할 때 key가 추가되어 있지 않았으니 unique한 key 추가 부탁드립니다!

2022-07-09 03:57 UTC, ChanhyukPark-Tech commented on src/components/Edit/Menus/PasswordEdit.tsx
> +        const data = await dispatch(changePassword(body)).unwrap();
확인 감사합니다!
에러처리를 87번째줄에서   setMsg(data.message); 로 성공했을때와 실패했을때 공통으로 진행하고 있습니다!
백엔드에서 에러메세지를 친절하게 data.message 라는 field 로 작성해주셔서 바로 사용만 하면 되는것 같습니다!

2022-07-09 03:58 UTC, ChanhyukPark-Tech commented on src/components/Edit/Menus/PasswordEdit.tsx
> +        const data = await dispatch(changePassword(body)).unwrap();
UX 측면에서 로그아웃 처리하고 다시 로그인하는것보다는 로그인 상태를 유지하는게 더 좋다고 개인적으로 생각했습니다!

2022-07-09 04:01 UTC, ChanhyukPark-Tech commented on src/components/Edit/Menus/PasswordEdit.tsx
> +            setMsg("두 비밀번호가 일치하는지 확인하세요");
정확한 플로우는 영인님이 말씀해주신대로 
기존 비밀번호 일치 => 두 비밀번호 확인 일치 이지만,
이렇게 되면 비밀번호가 기존의 것과 일치한지만 판단하는 REST API 가 필요하게 될 것 같습니다.
기존의 것과 일치한다면 다시 클라이언트에서 작성한 두가지 비밀번호가 서로 일치하는지 확인하고 정말 비밀번호를 바꿔달라는 REST API 를 호출하는게 맞는것 같습니다.

하지만 2번의 네트워크 통신과 복잡한 로직보다는 한번의 네트워크 통신으로 처리하기위해서 
클라이언트에서 두 비밀번호의 일치를 확인한 후 일치한다면 비로소 백엔드로 API 를 호출하는 방향을 택했습니다! 😃

2022-07-09 04:03 UTC, ChanhyukPark-Tech commented on src/components/Edit/Modal/ProfileGenderModal.tsx
> +        >
초기에 반응형을 고려하지 않기로하여서, 반응형은 따로 고려하지 않았습니다!

2022-07-09 04:04 UTC, ChanhyukPark-Tech commented on src/components/Edit/Section/EditItemInput.tsx
>  const EditItemInput = ({ item, guide }: EditItemProps) => {
확인 감사합니다!
[bf96656](https://github.com/Instagram-Clone-Coding/React_instagram_clone/pull/72/commits/bf96656fd9788afbb849bad92921644d68da0d2d)

2022-07-09 04:04 UTC, ChanhyukPark-Tech commented
> 커밋 내역에 해당하지 않지만
> 
> 1. 비밀번호 변경 버튼의 위치가 input과 동일하게 왼쪽 끝에 위치하도록 해주세요!
> 2. 비밀번호 변경 버튼을 클릭하여 비동기 호출 시 사용자가 현재 상황을 인식할 수 있도록, 인스타그램과 같이 `fullfilled` 혹은 `rejected` 되기 전 `pending` 동안에는 로딩 모양으로 버튼을 바꿔주세요!(이를 적용하려면 loading state를 사용해야 하기 때문에 해당 컴포넌트에서 이를 따로 만들거나 unwrap 처리를 하지 말고 전역 loading state를 활용하셔야 할 것 같습니다!)


확인 감사합니다!
[3a588ea](https://github.com/Instagram-Clone-Coding/React_instagram_clone/pull/72/commits/3a588ea46e03b8290a4f5cd69dbec1add934e265)

[db02768](https://github.com/Instagram-Clone-Coding/React_instagram_clone/pull/72/commits/db027686c16b9bf5c5d42908847c17687aa54609)

2022-07-10 13:11 UTC, kimyoungyin commented on src/components/Edit/Menus/PasswordEdit.tsx
> +            setMsg("두 비밀번호가 일치하는지 확인하세요");
넵 기존에 만들어둔 api에 따르기로 하신 거군요 알겠습니다!

2022-07-27 11:46 UTC, kimyoungyin approved these changes

2022-07-27 11:47 UTC, merged